before_script:
  - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
  

stages:
  - lint
  - deploy

js_lint:
  image: node:latest
  stage: lint
  script:
    - npm install
    - npm run lint

# php_lint:
#   image: php:latest
#   stage: lint
#   script:
#     - bash installPHP.sh
#     - php composer.phar run lint

deployToAWS:
  only:
    - master
    - develop
  stage: deploy
  script:
    - bash deploy.sh