before_script:
  - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
  - npm install

stages:
  - lint

js_lint:
  image: node:latest
  stage: lint
  script:
    - npm run lint

# deployToAWS:
#   only:
#     - master
#     - develop
#   stage: deploy
#   script:
#     - bash deploy.sh